### ISSUE TITLE
Incorrect casing for "github-token" example in the readme

### ISSUE THREAD

**Issue by D4nte** [thomaseizinger/create-pull-request#38]
It looks like github action expects kebab casing:

I get the following warning when using this action in: https://github.com/D4nte/comit-rs/actions/runs/340812607

```
Check warning on line 1 in .github

@github-actions github-actions / Draft a new release of cnd

.github#L1

Unexpected input(s) 'GITHUB_TOKEN', valid inputs are ['github-token', 'head', 'title', 'base', 'draft', 'body', 'reviewers']
```

**Comment by thomaseizinger** [comment]
Yes, looking at the current code, I think this just needs to be removed and we need to document that we expect the `GITHUB_TOKEN` **env** variable.

**Comment by teebu** [comment]
Any update on this? having issues getting this to work.

**Comment by thomaseizinger** [comment]
```
name: "Create PR"
on: push

jobs:
  create-pr-on-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1.0.0
    
    - name: Create pull request
      uses: thomaseizinger/create-pull-request@master
	  env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        head: ${{ github.ref }}
        base: master
        title: "An automatically created PR!"
```

Should do it but then I also think this is actually implicit and you don't need to specify anything in regards to `GITHUB_TOKEN` unless you want to set a personal access token.
